config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  #devise_for :users
  root "welcome#index"
  get '/welcome', to: "welcome#index"
  get 'search_stock', to: "stocks#search"
  
  #get 'my_portfolio',to: 'users/sessions#my_portfolio'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get 'my_portfolio' => 'users/sessions'
    get 'my_friends' => 'users/sessions'
    get 'search_friend'=> 'users/sessions#search'
    get 'view_profile' => 'users/sessions#show'
    get 'passwords' => 'users/passwords#new'
    get 'refresh' => 'users/sessions'
    get 'order_up' => 'users/sessions'
    get 'order_down' => 'users/sessions'
    get 'web_search' => 'users/sessions'
    end

end
#do
 # devise_for :users
  #root "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#end

app/views/layouts/_background.html.erb
<% if @new_user %>
  "new_user"
<% elsif @sign_up %>   
  "new_account"
<% elsif @new_pass %>   
  "new_pass"
<% end %>

app/views/layouts/_messages.html.erb
<div class="container">
	<% if notice %>
		<div class='alert alert-success'>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
			<%= notice %>
		</div>
		
	<% end %>
	<% if alert %>
		<div class='alert alert-danger'>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
			<%= alert %>
		</div>

	<% end %>
</div>

app/views/layouts/_navigation.html.erb
<% if current_user %>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container">
			<%= link_to 'FinanceTracker' , root_path, class: 'navbar-brand' %>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item <%= nav_status(request.path, my_portfolio_path) %>">
						<%= link_to "My Portfolio", my_portfolio_path, class: 'nav-link'%>
					</li>

					<li class="nav-item <%= nav_status(request.path, my_friends_path) %>"> 
						<%= link_to "My Friends", my_friends_path, class: 'nav-link'%> 
					</li>

					<li class="nav-item <%= nav_status(request.path, edit_user_registration_path) %>">
						<%= link_to "Edit profile", edit_user_registration_path, class: 'nav-link' %>
					</li>
				</ul>

				<ul class="navbar-nav ml-auto">
					<li class="nav-item user-name">
						<span class="fa fa-user"></span>
						<%= current_user.full_name %>
					</li>

					<li class="nav-item">
						<%= link_to("Logout", destroy_user_session_path, class: "btn btn-danger logout-button", method: :delete) %>
					</li>
				</ul>

				<%=form_tag web_search_path, class:"form-inline my-2 my-lg-0", method: :get do %>
				<%=text_field_tag :query, params[:query], placeholder: "Search", autofocus: true, class: "form-control mr-sm-2"%>
				<%=button_tag :Search, type: :submit, class: "btn btn-outline-success my-2 my-sm-0" %>
				<% end %>
			</div>
						
		</div>
	</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navigation' %>	
	
  <body class= <%=render partial: "layouts/background" %> >
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>